feat(deps): Add Nextcloud 28 support on master
nextcloud/suspicious_login pull request #800
Opened 2023-05-17 13:22 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2023-05-17 13:24 UTC, ChristophWurst approved these changes

2023-05-17 13:50 UTC, ChristophWurst requested changes

2023-05-17 14:20 UTC, st3iny commented on package.json
> +  "version": "5.1.0-dev",
```suggestion
  "version": "6.0.0-dev",
```

See above.

2023-06-12 05:32 UTC, st3iny commented on appinfo/info.xml
> +	<version>5.1.0-dev</version>
Done

2023-06-12 05:32 UTC, st3iny commented on package.json
> +  "version": "5.1.0-dev",
Done

2023-06-12 05:32 UTC, st3iny approved these changes

2023-06-12 05:37 UTC, st3iny commented
CI fix at https://github.com/nextcloud/suspicious_login/pull/802.

2023-06-12 05:37 UTC, merged